# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test Pylenium with Selenoid

on:
  push:
    branches: [patch-1]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install poetry
          # install dependencies from pyproject.toml
          poetry install

      - name: Lint with flake8
        run: |
          # Using .flake8 file
          poetry run poe lint

      - name: Run Unit Tests
        run: |
          poetry run pytest tests/unit

      - name: Start Selenoid Server
        # https://github.com/marketplace/actions/start-selenoid-server?version=v2
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: |
            --args "-timeout 60s"

      - name: Run UI Tests
        run: |
          poetry run pytest tests/ui --remote_url "http://localhost:4444/wd/hub"
